services:
  mongo:
    image: mongo:6.0
    container_name: jobTracker-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
